versotile-org/verso

- src/main.rs
The type should be cocoa::base::BOOL not bool.
> fix: Compile error

- src/app.rs
- src/webview.rs
> Support offscreen rendering

- .github/workflows/build.yml
Not yet passing but it would be nice to have CI checks.
https://github.com/orhun/yippee/actions/runs/8232365694/job/22509654900
Currently it is failing due to some `mozangle` error, maybe a missing dependency. Any ideas?
> Add automated build check

- .github/workflows/build.yml
> build: add nightly release to CN Cloud

- Cargo.lock
- Cargo.toml
- build.rs
- src/app.rs
- src/lib.rs
- src/main.rs
- src/test.rs
- src/webview.rs
- src/window.rs
Not too much of a code change... this PR is mostly about fixing up doc lines.
> Small cleanup

- .github/workflows/doc.yml
unfortunately current process wipes the custom domain.
this PR fixes it
> fixing doc generation (CNAME issue)

- Cargo.lock
- Cargo.toml
- src/app.rs
- src/window.rs
> feat(clipboard): support clipboard, fixed #70

- Cargo.lock
- Cargo.toml
- src/compositor.rs
- src/verso.rs
We needs webgl becasue webxr. This PR tried to add a dummy implementation and disable webgl
> chore: disable WebGL by default

- Cargo.lock
- Cargo.toml
- src/webview.rs
I added a logic to handle missing url protocols when entering url from the address bar.
https://github.com/versotile-org/verso/issues/124
> handle http protocols

- README.md
> Update README.md. Fixed a typo.

- README.md
I think you intended to say "while growing it into a mature browser one day", which would mean the goal is to at some point in the future grow verso into a mature browser.
The way it is currently written "while growing it into a mature browser in one day" implies that the task of growing verso into a mature browser will be completed with a single day of work.
I'm very excited for this project :)
Loving the recent progress in new browser engines with Servo and Ladybird.
> Grammatical fix in README

- Cargo.toml
Added a release profile with lto enabled to the Cargo.toml
#129
> Adding release profile with lto

- .github/workflows/doc.yml
Updated doc workflow to use Nix for dependency
> chore: update doc workflow dependency

- Cargo.toml
- src/compositor.rs
- src/keyboard.rs
- src/main.rs
- src/touch.rs
- src/verso.rs
- src/webview.rs
- src/window.rs
I ran `cargo clippy` on the codebase and applied it's suggestions. I also implemented the `Default` trait for the `TouchHandler` inside _touch.rs_ and moved the `new()` function over to the `default()` function.
> Applied clippy suggestions

- README.md
Reverts versotile-org/verso#143
Fixes #184
> Revert "fix: README get flatpak deps from flathub in flatpak-builder command"

- Cargo.lock
- Cargo.toml
- src/compositor.rs
- src/verso.rs
Font is now using IPC shared memory to share the data
> chore: bump servo to 58f34ad

- src/config.rs
Fix https://github.com/versotile-org/verso/pull/229#discussion_r1838381596
> Fix x and y being on long name instead of short

- src/config.rs
- src/verso.rs
> Allow enable and set servo devtools port from cli

- Cargo.lock
- Cargo.toml
- resources/prefs.json
- src/compositor.rs
- src/verso.rs
Thanks to https://github.com/servo/servo/pull/34241, we can set webxr to disable by default now.
> Move webxr to disable by default

- src/config.rs
- src/main.rs
- src/verso.rs
This PR also make it possible to run verso without any resource file.
> Add resource_dir argument

- .github/workflows/doc.yml
The cache seemed to accumulate the results and get bigger and bigger, and it's running out of disk space by restoring the cache
> build: remove doc nix cache

- Cargo.toml
- src/compositor.rs
- src/context_menu.rs
- src/webview.rs
- src/window.rs
This PR tries to update some states and clean up the code blocks on each platform.
The documentation of context menu is also added.
> Update context menu states

- Cargo.lock
- Cargo.toml
- src/compositor.rs
Updated compositor to use `webrender_api::units::DevicePixel` instead of `style_traits::Device`.
> chore: Update servo to `7489e3d`

- .gitattributes
HTML files have moved into the components subfolder under resources and being counted again, so we are a HTML project now lol.
> chore: update gitattribute linguist

- Cargo.lock
- Cargo.toml
- resources/prefs.json
As a result several additional changes has been made:
- `style` crate is updated to `2024-12-04` branch
- `dom.xpath.enabled: false` is added to `pref.json`
- several thread pool related preference is also added to `pref.json`
> chore: Update servo to `af8f35f`

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
As a result msrv has now been bumped to 1.83.0
> chore: Update servo to `dd9164f`

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/verso.rs
- update `servo`
- update `stylo`
- update `headers`
- add `rustls` (for latest `net` crate)
> chore: update servo to `90c5685`

- Cargo.lock
- Cargo.toml
Seems like a rather uneventful update this time around.
> chore: Update servo to `7045630`

- Cargo.lock
- src/verso.rs
- verso/Cargo.toml
- verso/src/lib.rs
- versoview_messages/src/lib.rs
Implement what's mentioned in https://github.com/versotile-org/verso/pull/275#discussion_r1963116283
> Support running getters on multiple threads at the same time

- Cargo.lock
- Cargo.toml
- src/webview/webview.rs
Fixes #285
This is an initial implementation of File Dialog support using `rfd` crate.
There are however some improvements to be made, namely there's currently no indication of the file selected, therefore the usability suffers. We should open an issue at the Servo side to properly support displaying the selected file.
**Working example**
https://github.com/user-attachments/assets/59afa0a9-9814-4413-9858-82462af0e8a9
> feat: Implement File Dialog support
