src/app.rs, src/webview.rs
Move window event handler to each WebView so that we can easily support multiple windows in the future.
=> chore: move winit window event handler to WebView impl

src/webview.rs
Should check framebuffer before `present()`, otherwise the buffer will be cleaned after present and always falls into assert.
=> fix: check framebuffer status before present

Cargo.lock, Cargo.toml, src/app.rs, src/lib.rs, src/main.rs, src/webview.rs, src/window.rs
This is the first refactoring to contain two web views, with one specialized for controlling applications.
We will add more functions to the panel web view in the future.
=> Add initial multiview support

.github/workflows/build.yml
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
`macos-latest` has pointed to `macos-14`
=> ci: use `macos-latest` to build aarch64 platform

README.md
I got error when running `cargo run`
```bash
pkg-config exited with status code 1
> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags harfbuzz
The system library `harfbuzz` required by crate `harfbuzz-sys` was not found.
The file `harfbuzz.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
The PKG_CONFIG_PATH environment variable is not set.
HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `harfbuzz.pc`.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Should we tell the user to install `harfbuzz`?
=> chore: add harfbuzz to Homebrew installation in README.md

.github/workflows/doc.yml
By issue https://github.com/versotile-org/verso/issues/22
Fairly stable CI feature added.
It will deploy to the [docs](https://github.com/versotile-org/docs.versotile.org/tree/docs) repository on the branch `docs`...
... and the docs will be on the site https://docs.versotile.org/verso
Now, while it is tested and worked, after the wipe github experiencing some issues with github pages, so deploy should wait a little bit: [gh-issue](https://github.com/orgs/community/discussions/130206)
Some more improvement also possible, i.e.:
https://github.com/versotile-org/verso/issues/60
=> generate and deploy docs

README.md, shell.nix
Current build step is: `nix-shell shell.nix --run 'nixGL cargo r'`
=> Add nix support

Cargo.lock, Cargo.toml
`servo` seems to update `surfman` to 0.9.5 so the feature `sm-raw-window-handle` is now changed to `sm-raw-window-handle-05` accompanying this change.
=> chore: update servo 5e59988

.github/workflows/build.yml, org.versotile.verso.yml
Issue: #99 
- Update flatpak mozjs archive version: `mozjs-sys-v0.115.13-2` -> `mozjs-sys-v0.128.0-6`
- Replace linux binary release with flatpak single-file-bundle
=> ci(flatpak): add flatpak single-file-bundle release, close #99

Cargo.lock, Cargo.toml, src/compositor.rs, src/main.rs, src/verso.rs, src/webview.rs, src/window.rs
This PRs adds initial multi-window support.
There are some known issues we might open in follow up issues:
- Closing x11 window can cause Xerror and even crashs.
- Closing macOS window will segfault due to https://github.com/servo/surfman/pull/304
- Wayland spawning new window in the same window.
- CreateOrUpdateWebView may change to old pipeline, but we won't update it to "loaded"
=> feat: multi-window support

.github/workflows/build.yml
It seems we produce way too many unused build. Let's just publish weekly instead.
=> chore: update nightly period to weekly

src/compositor.rs, src/verso.rs, src/webview.rs, src/window.rs
It seems better to call window's painting order directly to get the right order.
This PR also fixes #114
=> chore: remove painting order method in compositor

README.md
This slims down the README by removing the lines where you manually install the flatpak runtimes beforehand.
The installation is now done automatically in the flatpak-builder command.
remove trailing whitespace
=> fix: README get flatpak deps from flathub in flatpak-builder command

.github/ISSUE_TEMPLATE/bug_report.md
Closes #154
This adds a bug report template to let reporter list out steps to reproduce and their system info.
=> docs: add bug_report.md template

.github/workflows/build.yml, Cargo.lock, Cargo.toml, rust-toolchain.toml
Rust toolchain is upgraded to 1.80.1 to be in sync with servo.
Closes #159 .
=> Update servo e078353

Cargo.lock, Cargo.toml, src/keyboard.rs
Part of #69 to support more key mappings
Also 
- bump `env_logger: 0.10 -> 0.11`, 
- add macros to generate code in `keyboard.rs` to conveniently generate mappings
=> feat: add some more keyboard mappings

Cargo.lock, Cargo.toml, src/compositor.rs
compositor has now been updated to use `CrossProcessInstant` instead of `u64` system time.
=> chore: Update servo to 4d0bef0

Cargo.lock, Cargo.toml
Accompanying this change `stylo` has been upgraded to `2024-09-02` to be in line with `servo`.
=> chore: Update servo to 9f2306f

.github/workflows/build.yml
It didn't update the apt, so it's trying to fetch outdated and removed dependency
=> build(flatpak): fix flatpak apt dependency

src/compositor.rs, src/verso.rs
This is the preparation work for multi-window able to render all windows at the same time.
Current compositor can only render one window at the moment.
This PR set all window to the same document ID for now.
We will try to improve webrender upstream to support multi-document rendering for next step.
=> feat: add document ID to windows

src/config.rs
**Issue:**
Verso crashes when launching.
**Root cause:**
We are using `initial-url` as long name option below, but only register `url` to getopts.
=> fix: cli no opts initial-url

src/compositor.rs, src/main.rs, src/window.rs
Insane amount of time has been spent into this but we finally did it!!!!!!!!!!
See comments of https://github.com/versotile-org/verso/issues/194#issuecomment-2456968920 to watch how smooth it is right now.
Windows is safe already so I didn't change the behavior. Perhaps we can think about unified solution in the future.
=> fix: smooth resizing on Linux and macOS

org.versotile.verso.yml
=> Build and install verso for flatpak

src/compositor.rs, src/main.rs, src/verso.rs, src/window.rs
I've tested on [Linux](https://x.com/Yu_Wei_Wu/status/1854468340225597668) and [macOS](https://x.com/Yu_Wei_Wu/status/1854366143831757289). Just need to check Windows is still safe and I'll clean up and move to PR.
=> feat: smooth resizing

.github/workflows/build.yml
Fix nightly release failed when uploading Windows NSIS bundle
=> build: use versoview as windows nsis name

src/compositor.rs, src/config.rs, src/verso.rs
=> Allow changing user agent through CLI

.gitignore, Cargo.lock, Cargo.toml, resources/context_menu.html, src/compositor.rs, src/context_menu.rs, src/webview.rs, src/window.rs
=> feat(context-menu): add linux webview context menu

resources/components/prompt/prompt.css, src/config.rs
follow up: #250
- slightly shrink the size of the prompt
- set min window size to at least show all panel UI
=> refactor: set min window size to show all panel options

.cargo/config.toml, Cargo.lock, Cargo.toml, src/webview/webview.rs
This is still WIP, accompanying this several changes has been made:
- `mozjs_sys` has been added to `.cargo/config.toml`
- `PromptDefinition::Credentials` are added in `webview.rs` to be handled
We can maybe merge this for now and implement the handling for `PromptDefinition::Credentials` later.
=> chore: Update servo to `9156ee3`

resources/components/prompt/http_basic_auth.html, src/webview/prompt.rs, src/webview/webview.rs, src/window.rs
Remaining issues:
- ~~Canceled prompt keeps showing up and hang (switch tabs and back will fix it)~~ fixed
- After a bad authentication, it'll still fail even if you enter the correct account info (should fix in servo)
- Credential prompts in servo blocks other tabs webview process (should fix in servo)
=> feat(dialog): add HTTP basic authentication

.github/workflows/build.yml
`ubuntu-latest` now uses 24.04.1 which will break the build in #265 . We'll have to lock the ubuntu version for now and move with servo as they progress.
=> chore: lock build-linux runner at ubuntu-22.04

src/config.rs
Reference: https://github.com/versotile-org/verso/pull/269#discussion_r1926348744
=> Bring back `devtools_port` cli arg

Cargo.lock, Cargo.toml, src/compositor.rs, src/verso.rs, src/webview/prompt.rs, src/webview/webview.rs, src/window.rs
- To receive `contextmenu` event
- Linux WebView context menu is broken in this update because the `WebViewFocused` emits only when the mouse is clicking an element (such as \<input> or \<a>), so we can't close it properly. We used to focus webview by handling `EventDelivered` event, but it has been removed.
Will try to fix the issue in another PR.
=> chore: bump servo to 8cd280c

resources/components/context_menu.html, src/compositor.rs, src/webview/context_menu.rs, src/webview/webview.rs, src/window.rs
- Fix in #277, context menu not able to close from `WebViewFocused` event
- Create a context menu with a window size mask under the menu. If the user clicks on the mask, we send a message back to Verso to close the context menu.
- Move menu position calculation into `context_menu.html`
=> fix(linux): close context menu

src/webview/context_menu.rs, src/webview/webview.rs, src/window.rs
Issue: #225 
- Removed the code that shows context menu when mouse clicks on the window
- Show context menu when Servo fires `ShowContextMenu` to embedder
=> fix(contextmenu): show context menu when receiving `ShowContextMenu`

resources/components/prompt/allow_deny.html, resources/components/prompt/http_basic_auth.html, src/webview/prompt.rs, src/webview/webview.rs
`AuthenticationResponse` now doesn't take `Option<String>` anymore, hence we should return empty string for parsing
=> fix(prompt): auth action response format

Cargo.lock, Cargo.toml, src/compositor.rs, src/touch.rs, src/verso.rs, src/webview/webview.rs, src/window.rs
This is a quite hefty update with `TouchEvents` and `EmbedderMsg` changes:
- `Opts.wait_for_stable_image` is introduced to replace `Opts. exit_after_load`.
- Shutdown related compositor handling is now triggered through `EmbedderMsg` instead of `CompositorMsg`.
- `TouchEventAction` is now renamed as `TouchEventType`.
- The `action` stored in `TouchEvent` is now named `event_type` with the type of  `TouchEventType` and with the changes of the `TouchEvent` struct the touch event handling has been restructured.
- `WebResourceResponseMsg::Body` has been reworked into `WebResourceResponseMsg::SendBodyData` which takes in `Vec<u8>` directly now.
=> chore: Bump servo to `47f6c50`

src/verso.rs, src/webview/webview.rs, src/window.rs
Fix the regression about `on_web_resource_requested` from #284
So it turned out, the exit is still working just fine, but `on_web_resource_requested` broke
=> Properly migrate `WebResourceRequested` handler

src/verso.rs, src/webview/webview.rs, src/window.rs
This is an early implementation of IME support thus the draft state.
We need to explicitly enable IME support to winit window so that winit will pass [`ImeEvent`](https://docs.rs/winit/latest/winit/event/enum.Ime.html) with `set_ime_allowed`. We can pass this event matching Servo's own [`ImeEvent::Composition`](https://github.com/servo/servo/blob/73507f58e63b130d91fcf6f1da13e643b9c469d3/components/shared/embedder/input_events.rs#L179).
=> feat: Support IME event

.github/workflows/build.yml, Cargo.lock
Windows CI failed to build `mozangle`: https://github.com/versotile-org/verso/actions/runs/13723976379/job/38385860116
~~This might be caused by the llvm version bump to 20.1.0 on March 7~~
=> ci(windows): upgrade and use github runner built in LLVM

src/config.rs, verso/src/builder.rs, verso/src/lib.rs, verso/src/main.rs, versoview_messages/src/lib.rs
#290 introduced a lot of initial settings and this PR adds in a builder as a more stable API to create verso controller with settings
=> Introduce `VersoBuilder` for more stable controller creation
